version: '3'
services:
  arubaautomation:
    container_name: arubaautomation
    image: jmetts/arubaautomation:test
    depends_on:
      - mysql
    volumes:
      - /docker/arubaautomation/var/www:/var/www
      - /docker/arubaautomation/tftp:/home/tftpboot
    networks:
      supernet:
        ipv4_address: 172.28.0.4
    ports:
      - "8080:8080"
      - "67:67"
      - "69:69"
      - "5000:5000"
      - "161:161"
      - "514:514"
#    dns:
#      - 192.168.30.3
#      - 192.168.200.4
    environment:
      TZ: "America/Chicago"
      #    user: 1000:1000
    restart: unless-stopped
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Testing123
      MYSQL_USER: aruba
      MYSQL_PASS: ArubaRocks
    volumes:
      - /docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      supernet:
        ipv4_address: 172.28.0.5
    restart: unless-stopped

networks:
  supernet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16